export { default as Bar } from './Bar'
export { default as Workspace } from './Workspace'
export { default as Time } from './Time'
export { default as Cpu } from './Cpu'
export { default as Spotify } from './Spotify'
export { default as Battery } from './Battery'